### ISSUE TITLE
Minor adjustments before being released in Devchecklists.

### ISSUE THREAD

**Issue by felipefarias** [r0f1/ml_checklist#1]
Hey Florian! First of all, thanks for submitting your Explorative Data Analysis checklist! 

We will love to release it on Devchecklists. But before it, can you please take a look at our [guide for submitting new checklists?](https://devchecklists.com/creating-new-checklist/) Basically, you will need to rename your file to checklist-en. 

We still working in some minor improvements before officially launch it. So any feedback is appreciated. Let me know if you need more information.

**Comment by r0f1** [comment]
No, I won't rename it, because then it won't be displayed properly on Github.

**Comment by felipefarias** [comment]
No worries. You can keep your readme as it is. A workaround here is to create a `devchecklists` folder and add the `checklist-en` file into it. Let me know if this solution is possible. Additionally, this will make possible that people start to translate your checklist for different languages, as happened with our [celery-tasks-checklist](https://github.com/vintasoftware/celery-tasks-checklist) that was translated in 3 additional languages.
